### PR TITLE
Added redux store file

### LINKED ISSUE #45: Setup redux/store.ts

### PR DESCRIPTION
**Pull request by dyazdani**
Closes #45 

Not sure the best way to test this. Open to your recommendations and can add proof of testing afterwards.

### CODE REVIEW

**Review by paloobi — APPROVED** [review]
store lgtm

**Review by paloobi — CHANGES_REQUESTED** [review]
Actually, I would recommend at least connecting it to the app at the same time as this, and ensuring the app runs.

Not being able use any of the rtk features in the app is going to make it hard to test all the other PRs

**Comment by dyazdani** [comment]
What exactly do you mean when you say "connecting it to the app"? Do you mean using state from `store.ts` in some way in `App.tsx`? Like perhaps with useSelector?

**Comment by paloobi** [comment]
I mean that this store is not currently loaded in the app anywhere.

https://redux-toolkit.js.org/tutorials/quick-start#provide-the-redux-store-to-react

**Comment by dyazdani** [comment]
I'm going to close this PR because the store was added to the app in the features/api.tsx branch, which we will merge into main.

**Pull request closed without merging**
